In [2]:
!pip install pandas

Requirement already satisfied: pandas in /home/sonia/miniconda3/lib/python3.13/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /home/sonia/miniconda3/lib/python3.13/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/sonia/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/sonia/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

icd_d_p_pairs_df = pd.read_csv("data/raw/icd_d_p_pairs.csv")
trainig_condification_data_df = pd.read_csv("data/raw/training_codification_data.csv")

In [4]:
# Cross-reference rows present in both dataframes using the "Code" column
cross_referenced_df = pd.merge(
    icd_d_p_pairs_df,
    trainig_condification_data_df,
    on="Code",
    how="inner",
    suffixes=("_icd", "_training")
)

print(f"Matched rows: {len(cross_referenced_df)}")
cross_referenced_df.head()

Matched rows: 9943

,Code,D_P,Description,Literal
0,A020,D,Enteritis debida a Salmonella,Gastroenteritis aguda por Salmonella entérica
1,A045,D,Enteritis debida a Campylobacter,campylobacter jejuni
2,A080,D,Enteritis debida a rotavirus,gea Rotavirus
3,A080,D,Enteritis debida a rotavirus,Rotavirus
4,A09,D,"Gastroenteritis y colitis infecciosas, no espe...",A09

In [5]:
#save the cross-referenced dataframe to a new CSV file
cross_referenced_df.to_csv("data/utils/cross_referenced_data.csv", index=False)

In [6]:
# Cross-reference rows present in both dataframes using the "Code" column now for processed data
p_icd = pd.read_csv('data/preprocessed/icd_preprocessed_descriptions.csv')
p_train = pd.read_csv("data/preprocessed/preprocessed_data.csv")

preprocessed_cross = pd.merge(
    p_icd,
    p_train,
    on="Code",
    how="inner",
    suffixes=("_Description", "_Literal")
).loc[:, ["Code", "D_P", "processed_Description", "processed_Literal"]]

print(f"Matched rows: {len(preprocessed_cross)}")
preprocessed_cross.head()

Matched rows: 9943

,Code,D_P,processed_Description,processed_Literal
0,A020,D,enteritis debida a salmonella,gastroenteritis aguda por salmonella enterica
1,A045,D,enteritis debida a campylobacter,campylobacter jejuni
2,A080,D,enteritis debida a rotavirus,gastroenteritis aguda rotavirus
3,A080,D,enteritis debida a rotavirus,rotavirus
4,A09,D,"gastroenteritis y colitis infecciosas, no espe...",a09

In [7]:
preprocessed_cross.to_csv("data/utils/preprocessed_cross.csv", index=False)