In [41]:
import pandas as pd

final_train = pd.read_csv('data/utils/icd10_training_set.csv')

In [42]:
final_train.head()

,Code,D_P,processed_Description,processed_Literal
0,A020,D,enteritis debida a salmonella,gastroenteritis aguda por salmonella enterica
1,A045,D,enteritis debida a campylobacter,campylobacter jejuni
2,A080,D,enteritis debida a rotavirus,gastroenteritis aguda rotavirus
3,A080,D,enteritis debida a rotavirus,rotavirus
4,A09,D,"gastroenteritis y colitis infecciosas, no espe...",a09

## Children descriptions as subclasses

In [43]:
# Descriptions surrounded by quotes are considered children of a general description
children = final_train['processed_Description'].map(repr)
children

0                         'enteritis debida a salmonella'
1                      'enteritis debida a campylobacter'
2                          'enteritis debida a rotavirus'
3                          'enteritis debida a rotavirus'
4       'gastroenteritis y colitis infecciosas, no esp...
                              ...
9938    'otros procedimientos en region del tronco, pr...
9939    'otros procedimientos en region del tronco, pr...
9940    'otros procedimientos en region del tronco, pr...
9941    'otros procedimientos en region del tronco, pr...
9942    'otros procedimientos, otro metodo, aislamient...
Name: processed_Description, Length: 9943, dtype: object

In [44]:
children_train = final_train[["Code", "D_P"]].copy()
children_train['children_Descriptions'] = children
children_train['processed_Literal'] = final_train["processed_Literal"]
children_train.head()

,Code,D_P,children_Descriptions,processed_Literal
0,A020,D,'enteritis debida a salmonella',gastroenteritis aguda por salmonella enterica
1,A045,D,'enteritis debida a campylobacter',campylobacter jejuni
2,A080,D,'enteritis debida a rotavirus',gastroenteritis aguda rotavirus
3,A080,D,'enteritis debida a rotavirus',rotavirus
4,A09,D,"'gastroenteritis y colitis infecciosas, no esp...",a09